version: "3.9"

services:

  # Development container
  dev:
    build:
      context: .
      dockerfile: example_project/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/example_project
    tty: true
    stdin_open: true
    depends_on:
      - redis
    command: "/bin/bash"

  # Standalone Redis server
  redis:
    image: redis:7
    ports:
      - "6379:6379"
